name       : xa
version    : 2.3.9
release    : 1
source     :
    - http://www.floodgap.com/retrotech/xa/dists/xa-2.3.9.tar.gz : 8d3097d3b75adf4305d7d5c8e8f2568a7176cb348bcc50006cfc58378540c555
license    : GPL-2.0-or-later
component  : programming
summary    : Cross-assembler for 6502 microprocessor
description: |
    Cross-assembler for 6502 microprocessor
setup      : |
    %make
build      : |
    %make
install    : |
    %make_install DESTDIR=$installdir/usr
